title: Krisalay Thakur
logo: /assets/img/logo.png
description: A versatile high energy software design and developer with a strong driving force for implementing Innovative systems that solve real business problems. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
